### ISSUE TITLE
Could you add a demo?

### ISSUE THREAD

**Issue by jnachtigall** [frankwallis/react-slidedown#1]
Thanks for react-slidedown. I came across your project searching some react-like alternative for jQuery's `slideDown`. I think I'll just use jQuery from within react, but looking at your README i thought: Could you add a little, simple demo at codepen or https://codesandbox.io/ ? A simple demo page tells more than thousands words :) 

If possible maybe also a browser matrix, e.g. is IE 10/11 supported?

**Comment by frankwallis** [comment]
Thanks for the feedback, it's appreciated :)

I have added a link to the live example project running in CodeSandbox (https://ykxm1vz5vv.codesandbox.io/) and a note about browser compatibility to the README.
