### ISSUE TITLE
SlideDown stops working after several clicks

### ISSUE THREAD

**Issue by blu3printchris** [frankwallis/react-slidedown#11]
Having a weird bug with this:

My `SlideDown` contains a parent `div` which maps an array to show details. Now after a few clicks to open/close the `SlideDown`, the parent `div` will display behind the rest of my other `SlideDown` components below it rather than pushing them down the page. Another click will push them down the page but then any further clicks the `SlideDown`  just stops working. It won't collapse or expand my parent div leaving it stuck in an open state. 

I cannot figure out why this is happening, as it happens at random times.

**Comment by cristian-sima** [comment]
true

**Comment by frankwallis** [comment]
Thanks for raising this, I am seeing it too now. I shall investigate..

**Comment by blu3printchris** [comment]
Sorry for being so vaguein my initial report, but I wasn't too sure what was causing this. I now am. We use a package called Radium. When we export our component wrapped in Radium then this causes any SlideDown components in the main component to adapt weird behaviour!!

**Comment by frankwallis** [comment]
It seemed to be triggered when an update was fired during unmounting. I believe this issue is fixed in 2.4.1.
