### ISSUE TITLE
Opened item does not close

### ISSUE THREAD

**Issue by Koziolek** [frankwallis/react-slidedown#24]
Hi, 

I have code as below:

```
const KnowledgeItem = ({title: title, text: text}) =>{
    const [open, setOpen] = useState(null);
    const textBox = <div>{text}</div>;
    return(
        <div>
            <button onClick={()=> {
                setOpen(!open)
            }
            }>↓</button>
            <span>{title}</span>
            <SlideDown closed={open}>
                {open && textBox}
            </SlideDown>
        </div>
    );
};
```

Initial state of component is `null` and `SlideDown` is close. 
I click button and `open` change to `true` – `SlideDown` is now open .
I click button once again and `open` change to `false` – `SlideDown` is still open.

What I did wrong?

**Comment by frankwallis** [comment]
Hi - I think you shouldn't need to use _both_ the `closed` prop and the conditional `children` at the same time, so do either:
```
   <SlideDown>
      {open && textBox}
   </SlideDown>
```
or
```
   <SlideDown closed={!open}>
       {textBox}
   </SlideDown>
```
