### ISSUE TITLE
Support react 17

### ISSUE THREAD

**Issue by xavierraffin** [frankwallis/react-slidedown#37]
The project declare a peer dependency to react 16.
This prevent downstream projects to use react 17.

Can you please update to react 17?

Thank you very much

**Comment by xavierraffin** [comment]
I temporarily created a fork where I updated to react 17. But I had to remove testing stuff because you had test dependenies that does not support react 17:

https://github.com/xavierraffin/react-slidedown

I published a package here: https://github.com/xavierraffin/react-slidedown/packages/617417

**Comment by xavierraffin** [comment]
I wish you good luck for the migration (enzyme is the main pain point)

**Comment by OfirD1** [comment]
> I published a package here: https://github.com/xavierraffin/react-slidedown/packages/617417

I get an error for both:
`npm install @xavierraffin/react-slidedown@2.4.6`

and (in `package.json`, of course):
`"@xavierraffin/react-slidedown": "2.4.6"`

Full error:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@xavierraffin%2freact-slidedown - Not found
npm ERR! 404
npm ERR! 404  '@xavierraffin/react-slidedown@2.4.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Can you please fix it?

**Comment by xavierraffin** [comment]
@OfirD1 This is not me to solve anything. The error you have is because the package is published on Github and not on npm.
Just add a file `.npmrc` in your home or at the root of the project with the following content:

```
@xavierraffin:registry=https://npm.pkg.github.com
```

**Comment by OfirD1** [comment]
Thank you. Maybe it's worth adding this info under the "About this package" section.

**Comment by OfirD1** [comment]
Sorry, I guess I'm missing something, as it's still not working.

This is what I have in my `package.json`:
`"@xavierraffin/react-slidedown": "2.4.6"`

And in my `.npmrc` I have:
```
registry=https://registry.npmjs.org
@xavierraffin:registry=https://npm.pkg.github.com
```

Error I get:
```
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login
```

**Comment by xavierraffin** [comment]
The message you see is from npm not github. That means your npm cli is not talking to the good provider.

Here is mine (in both project root and my home directory):
```
//npm.pkg.github.com/:_authToken=ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
@xavierraffin:registry=https://npm.pkg.github.com
```

Here is the doc to use Github npm packages:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#publishing-a-package

Once your setup is working I'll update the README.

**Comment by xavierraffin** [comment]
Thank you @OfirD1 I am adding this to the README.

**Comment by frankwallis** [comment]
React 17 is now supported apologies for the delay

**Comment by xavierraffin** [comment]
Thank you very much @frankwallis!
When will you publish the updated package?
