### ISSUE TITLE
Cant resolve ./ChildMapping

### ISSUE THREAD

**Issue by tkolsen** [frankwallis/react-slidedown#7]
Error in ./~/react-slidedown/lib/TransitionGroup/TransitionGroup.js
Module not found: Error: Can't resolve './ChildMapping in ....

Getting this error message after the 1.4.0 release.

**Comment by tkolsen** [comment]
https://github.com/frankwallis/react-slidedown/blob/master/lib/TransitionGroup/TransitionGroup.jsx#L4

**Comment by tkolsen** [comment]
https://github.com/frankwallis/react-slidedown/blob/eb4dcac11fa416990f1b542f4d57e7c53195499a/package.json#L56

Wrong name on files here.
ChildMapping vs ChildMapping**s** in package.json

**Comment by frankwallis** [comment]
Fixed in 1.4.1 / 2.0.1.
