### ISSUE TITLE
SlideDown will sometimes keep displaying old content, even after it's removed

### ISSUE THREAD

**Issue by lukasgjetting** [frankwallis/react-slidedown#8]
Hi!

First of all, thank you so much for this library - it's just what I needed! 👍 

# The problem  
Though there is one problem. Sometimes, when quickly alternating 2 pages, they will both keep being visible - even though one shouldn't be there anymore.

You can see it fail [here](https://lukasgjetting.github.io/react-slidedown-update-while-sliding-test/) by clicking the "Click me to change page!" button multiple times quickly. You can also see the repository [here](https://github.com/lukasgjetting/react-slidedown-update-while-sliding-test).

![](https://i.imgur.com/CY5aq6D.png)

# The fix  
I think this has something to do with the component updating while animating, as it can be fixed by making `SlideDownContent` a `PureComponent`.

I don't see any downsides to changing it to a PureComponent, but I haven't tested it thoroughly. I just noticed it fixes my problem.

# The use case  
I am using this module to switch between 2 pages like in the test. When the user submits a form, it changes to page 2. If the form submit fails (maybe user entered wrong info?), the page changes back. This can sometimes happen very quickly - hence why this is a problem.

# The thanks  
Once again, thanks for this component! I (and many others) greatly appreciate the effort you put into it.

**Comment by lukasgjetting** [comment]
@frankwallis 

Yeah, I understand that components need to be kept in the DOM until the animation completes. *However*, I think the problem lies in the question "what if the animation never completes?" For example, if the state is updated multiple times, reverting the animation, and such?

Now, I haven't fully looked through the repo, so I don't know all the implementation details. But could it be that the `onCollapseComplete` handler (where elements are removed from the DOM) references an object (maybe the child component?), which has changed since the collapse started? That could mean that you are essentially "removing" an already non-existing component, but not removing the currently visible one.

Again, I haven't looked at the whole source, so this might be all wrong. In that case i apologise. ;)

Thank you for taking the time to investigate further!

**Comment by frankwallis** [comment]
The TransitionGroup uses _keys_ to identify the components and there is code to handle that scenario [here](https://github.com/frankwallis/react-slidedown/blob/master/lib/TransitionGroup/TransitionGroup.ts#L168). It is possible that there is a bug as this behaviour of the TransitionGroup was updated for react 16, but I do believe the example is working as expected.

**Comment by frankwallis** [comment]
I realise this was a long time ago... but there was an issue with old content sometimes being displayed when an update happened during unmounting. This should be fixed in 2.4.0.
